// Turns a generated fix into a real draft pull request.
//
// Safety rails (none of these are configurable per request):
//   - draft PRs only (falls back to a normal PR only where drafts aren't
//     available, e.g. private repos on GitHub Free); ServiceLens never merges
//   - branches are always created fresh under `servicelens/`; nothing else is written
//   - the fix must have been generated against the same file contents that are
//     on the base branch now (git blob SHA check), otherwise it's refused
//   - one PR per incident (idempotent) and at most one ServiceLens PR per repo per hour
//   - the repo must have the GitHub App installed; demo architectures never open PRs

import { prisma } from './prisma';
import { stringify } from './utils';
import { publish } from './realtime';
import { kick } from './jobs';
import { clientForRepo, GithubAppError } from './github/app';
import { generateFixPr, isCommittable, loadLatestFixPr, type FixPr } from './fix-pr';
import { AiUnavailableError } from './openrouter-stream';

const OPENING_LOCK_MS = 2 * 60_000;
const REPO_PR_WINDOW_MS = 60 * 60_000;
const PR_SYNC_MS = 60_000;

export class RemediationError extends Error {
  constructor(
    public code: 'demo' | 'no_fix' | 'stale_fix' | 'locked' | 'rate_limited' | 'conflict' | 'not_configured' | 'not_installed' | 'github',
    message: string,
    public status = 400,
    public installUrl?: string
  ) {
    super(message);
    this.name = 'RemediationError';
  }
}

export function composePrBody(fix: FixPr, incident: { id: string; title: string; architectureId: string }): string {
  const url = `${process.env.NEXT_PUBLIC_APP_URL ?? ''}/architectures/${incident.architectureId}/incidents/${incident.id}`;
  return [
    fix.prBody.trim(),
    '',
    '---',
    `Opened by **ServiceLens** for incident [${incident.title}](${url}).`,
    '',
    `- Generated from the incident's root-cause analysis against \`${(fix.baseSha ?? '').slice(0, 7)}\` on \`${fix.baseBranch}\`.`,
    '- Review carefully and run your tests before merging. ServiceLens never merges.',
  ].join('\n');
}

function mapGithubError(err: unknown): RemediationError {
  if (err instanceof RemediationError) return err;
  if (err instanceof GithubAppError) {
    if (err.code === 'not_installed') return new RemediationError('not_installed', err.message, 409, err.installUrl);
    if (err.code === 'not_configured') return new RemediationError('not_configured', err.message, 503);
    return new RemediationError('github', err.message, 502);
  }
  const e = err as { status?: number; message?: string };
  return new RemediationError('github', `GitHub: ${e.message ?? 'request failed'}`, 502);
}

export async function openFixPr(incidentId: string, opts: { byUserId?: string | null; auto?: boolean } = {}) {
  const incident = await prisma.incident.findUnique({
    where: { id: incidentId },
    select: {
      id: true,
      title: true,
      architectureId: true,
      architecture: { select: { demo: true } },
      service: { select: { repoUrl: true } },
    },
  });
  if (!incident) throw new RemediationError('no_fix', 'Incident not found', 404);
  if (incident.architecture.demo) throw new RemediationError('demo', 'The demo architecture never opens real pull requests.');
  if (!incident.service) throw new RemediationError('no_fix', 'This incident is not tied to a service repository.');

  const fix = await loadLatestFixPr(incidentId);
  if (!fix) throw new RemediationError('no_fix', 'Generate a fix first.', 409);
  if (!isCommittable(fix)) throw new RemediationError('stale_fix', 'This fix was generated by an older version. Regenerate it to open a PR.', 409);

  // Idempotent per incident; guard against double clicks / concurrent auto runs.
  const existing = await prisma.remediation.findFirst({
    where: { incidentId, kind: 'code_pr', status: { in: ['opening', 'opened'] } },
    orderBy: { createdAt: 'desc' },
  });
  if (existing?.status === 'opened') return existing;
  if (existing?.status === 'opening' && Date.now() - existing.createdAt.getTime() < OPENING_LOCK_MS) {
    throw new RemediationError('locked', 'A pull request is already being opened for this incident.', 409);
  }

  const recent = await prisma.remediation.count({
    where: { repoFullName: fix.repo, status: 'opened', createdAt: { gte: new Date(Date.now() - REPO_PR_WINDOW_MS) } },
  });
  if (recent > 0) {
    throw new RemediationError('rate_limited', `ServiceLens already opened a PR on ${fix.repo} in the last hour. Limit: one per repository per hour.`, 429);
  }

  let client;
  try {
    client = await clientForRepo(incident.service.repoUrl);
  } catch (err) {
    throw mapGithubError(err);
  }
  const { octokit, owner, repo } = client;

  const rem = await prisma.remediation.create({
    data: {
      incidentId,
      kind: 'code_pr',
      status: 'opening',
      repoFullName: `${owner}/${repo}`,
      baseBranch: fix.baseBranch,
      baseSha: fix.baseSha,
      branch: fix.branchName,
      title: fix.prTitle,
      auto: !!opts.auto,
      createdById: opts.byUserId ?? null,
    },
  });

  try {
    const base = fix.baseBranch!;
    const { data: ref } = await octokit.git.getRef({ owner, repo, ref: `heads/${base}` });
    const headSha = ref.object.sha;
    const { data: headCommit } = await octokit.git.getCommit({ owner, repo, commit_sha: headSha });

    // Conflict check + preserve file modes, from the base branch's current tree.
    const { data: tree } = await octokit.git.getTree({ owner, repo, tree_sha: headCommit.tree.sha, recursive: 'true' });
    const byPath = new Map((tree.tree ?? []).map((e) => [e.path, e]));
    const conflicts: string[] = [];
    for (const f of fix.files) {
      let sha = byPath.get(f.path)?.sha;
      if (!sha && tree.truncated) {
        const { data } = await octokit.repos.getContent({ owner, repo, path: f.path, ref: headSha }).catch(() => ({ data: null }));
        sha = data && !Array.isArray(data) ? (data as { sha: string }).sha : undefined;
      }
      if (sha !== f.blobSha) conflicts.push(f.path);
    }
    if (conflicts.length) {
      throw new RemediationError('conflict', `${conflicts.join(', ')} changed on ${base} since the fix was generated. Regenerate the fix.`, 409);
    }

    const blobs = await Promise.all(
      fix.files.map((f) =>
        octokit.git.createBlob({ owner, repo, content: Buffer.from(f.content!, 'utf8').toString('base64'), encoding: 'base64' })
      )
    );
    const { data: newTree } = await octokit.git.createTree({
      owner,
      repo,
      base_tree: headCommit.tree.sha,
      tree: fix.files.map((f, i) => ({
        path: f.path,
        mode: ((byPath.get(f.path)?.mode as '100644' | '100755' | undefined) ?? '100644'),
        type: 'blob' as const,
        sha: blobs[i].data.sha,
      })),
    });
    const { data: commit } = await octokit.git.createCommit({
      owner,
      repo,
      message: `${fix.prTitle}\n\n${fix.summary}\n\nServiceLens incident: ${incidentId}`,
      tree: newTree.sha,
      parents: [headSha],
    });

    // Always a fresh branch under servicelens/ — never touch an existing ref.
    let branch = fix.branchName;
    try {
      await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: commit.sha });
    } catch (err) {
      if ((err as { status?: number }).status !== 422) throw err;
      branch = `${fix.branchName}-${Date.now().toString(36)}`;
      await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: commit.sha });
    }

    const body = composePrBody(fix, incident);
    let draft = true;
    let pr;
    try {
      pr = (await octokit.pulls.create({ owner, repo, title: fix.prTitle, head: branch, base, body, draft: true })).data;
    } catch (err) {
      const e = err as { status?: number; message?: string };
      if (e.status !== 422 || !/draft/i.test(e.message ?? '')) throw err;
      draft = false; // drafts unavailable (e.g. private repo on GitHub Free)
      pr = (await octokit.pulls.create({ owner, repo, title: fix.prTitle, head: branch, base, body })).data;
    }

    const opened = await prisma.remediation.update({
      where: { id: rem.id },
      data: { status: 'opened', branch, prNumber: pr.number, prUrl: pr.html_url, prState: 'open', draft, syncedAt: new Date() },
    });
    await prisma.incidentEvent.create({
      data: {
        incidentId,
        type: 'fix_pr_opened',
        byUserId: opts.byUserId ?? null,
        payload: stringify({ url: pr.html_url, number: pr.number, repo: `${owner}/${repo}`, branch, draft, auto: !!opts.auto }),
      },
    });
    publish(incident.architectureId, 'incident_updated', { incidentId, prUrl: pr.html_url });
    await kick('notify', { incidentId, template: 'FixPRReady' });
    return opened;
  } catch (err) {
    const mapped = mapGithubError(err);
    await prisma.remediation.update({ where: { id: rem.id }, data: { status: 'failed', error: mapped.message } });
    throw mapped;
  }
}

// Latest PR for an incident; refreshes open/closed/merged from GitHub at most once a minute.
export async function latestRemediation(incidentId: string) {
  const rem = await prisma.remediation.findFirst({ where: { incidentId, kind: 'code_pr' }, orderBy: { createdAt: 'desc' } });
  if (!rem || rem.status !== 'opened' || !rem.prNumber || !rem.repoFullName) return rem;
  if (rem.prState !== 'open' || (rem.syncedAt && Date.now() - rem.syncedAt.getTime() < PR_SYNC_MS)) return rem;
  try {
    const { octokit, owner, repo } = await clientForRepo(`https://github.com/${rem.repoFullName}`);
    const { data } = await octokit.pulls.get({ owner, repo, pull_number: rem.prNumber });
    const state = data.merged ? 'merged' : data.state; // open | closed | merged
    const updated = await prisma.remediation.update({ where: { id: rem.id }, data: { prState: state, draft: !!data.draft, syncedAt: new Date() } });
    if (state !== 'open') {
      await prisma.incidentEvent.create({ data: { incidentId, type: state === 'merged' ? 'fix_pr_merged' : 'fix_pr_closed', payload: stringify({ url: rem.prUrl }) } });
    }
    return updated;
  } catch {
    return rem; // GitHub unreachable — show the last known state
  }
}

// Auto mode (Architecture.autoFixPr): runs after the RCA is ready.
export async function handleAutoFixPr(incidentId: string) {
  const inc = await prisma.incident.findUnique({
    where: { id: incidentId },
    select: { status: true, source: true, architecture: { select: { demo: true, autoFixPr: true } } },
  });
  if (!inc || inc.architecture.demo || !inc.architecture.autoFixPr) return { skipped: 'auto fix PRs off' };
  if (inc.status === 'resolved') return { skipped: 'incident already resolved' };

  try {
    let fix = await loadLatestFixPr(incidentId);
    if (!isCommittable(fix)) fix = await generateFixPr(incidentId);
    const rem = await openFixPr(incidentId, { auto: true });
    return { prUrl: rem.prUrl };
  } catch (err) {
    if (err instanceof AiUnavailableError) throw err; // transient — let the job retry
    const message = err instanceof Error ? err.message : String(err);
    await prisma.incidentEvent.create({ data: { incidentId, type: 'fix_pr_failed', payload: stringify({ error: message, auto: true }) } });
    return { failed: message };
  }
}
